#cloud-config

users:
  - name: lroot
    groups:
      - sudo
      - docker
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCjoZ5aCTPi2kTl5A8/GIKULN9PFVYa5JjcUl7LFje/praChNqXRzll6Hog4ruDj+adXorJXROSsHJcc6rs9DWQ7AgG+WHSHeEbYi8vx1jyqHsRJWmwD9irNFXOZ+Sy7FoGSPUKWu1/vcU9z33Z8Ai3WSVVI1ZXoW7dys5mzYCCsOFgN0c0L+n0KTHNfaTBdYERHFGycBLDmVwN8Eftzat/DJ1KMDMk58Gjh11xDOrUdbbpOCX5Am8ITappqvoWbsZtnMeSmI1B46m8aZ4qqwQUvocOHm627Oe6enkoXDQ2btPdvb2lkejYbxhq8N80Om3J+9TzVNt751j8k2QVn7QAOsR6ry+mP4XeG30xLMHn7RiET9d3FClJifzPC4OXj2Z2pQzp5otqGKwIb0hdC5NqRCrxMgoV/+dE13RUDX/pMlMsL33PqZeZDzE7E9dZoJ4dN2+ypUh3pwLwGpAyMLzkqDTNo4oTJtJiCoI+RVBg6MkAMp9/0c1OSAZBfNehh0CXGOixN5LvvDj05kgNLMQjNf/WvVCYrSrQLq9prcBBzczsbwK0sIsPqamvSe/fgUkeg8wonbsFmgVtfyHS7jMFUJemP85LfUxzoAxqomaiJl32qI0d+7np3nykgLgTatjE4b9HB5kryPqYMEMkoqT+Q3Vw9wftgNJcAy2hpgu29w==

write_files:
    - path: /etc/environment
      permissions: 0644
      content: |
        COREOS_PRIVATE_IPV4=$public_ipv4
        all_proxy=http://proxy.wdf.sap.corp:8080
        http_proxy=http://proxy.wdf.sap.corp:8080
        https_proxy=http://proxy.wdf.sap.corp:8080
        ftp_proxy=http://proxy.wdf.sap.corp:8080
        no_proxy=sap.corp,localhost,127.0.0.1,169.254.169.254,/var/run/docker.sock
    - path: /etc/systemd/system/docker.service.d/10-proxy.conf
      permissions: 0644
      content: |
        [Service]
        EnvironmentFile=/etc/environment
    - path: /etc/systemd/system/update-engine.service.d/10-proxy.conf
      permissions: 0644
      content: |
        [Service]
        EnvironmentFile=/etc/environment
    - path: /etc/ntp.conf
      permissions: 0644
      content: |
        server timehost1.wdf.sap.corp
        server timehost2.wdf.sap.corp
        server timehost3.wdf.sap.corp

        restrict default nomodify nopeer noquery limited kod
        restrict 127.0.0.1
        restrict [::1]
    - path: /run/systemd/network/10-dhcp.network
      permissions: 0644
      content: |
        [Network]
        DHCP=true

        [DHCP]
        UseMTU=true
        UseHostname=false
        UseRoutes=true
        CriticalConnection=true
    - path: /etc/ssl/certs/SAPNetCA.pem
      permission: 0644
      content: |
        -----BEGIN CERTIFICATE-----
        MIICrjCCAhegAwIBAgIEAQAAADANBgkqhkiG9w0BAQUFADBpMQswCQYDVQQGEwJE
        RTEPMA0GA1UEChMGU0FQLUFHMQ8wDQYDVQQLEwZTQVBOZXQxETAPBgNVBAMTCFNB
        UE5ldENBMSUwIwYJKoZIhvcNAQkBFhZtYWlrLm11ZWxsZXJAc2FwLWFnLmRlMB4X
        DTk4MDUwNDExNTYzNFoXDTE1MDcxODEyMDAwMFowaTELMAkGA1UEBhMCREUxDzAN
        BgNVBAoTBlNBUC1BRzEPMA0GA1UECxMGU0FQTmV0MREwDwYDVQQDEwhTQVBOZXRD
        QTElMCMGCSqGSIb3DQEJARYWbWFpay5tdWVsbGVyQHNhcC1hZy5kZTCBnzANBgkq
        hkiG9w0BAQEFAAOBjQAwgYkCgYEA35NK6MmmrCLvur4BDhugFe2FUfwJlvErafBb
        fvn+mkn8jxC/Kl0trTsQADJzYUnCdDLyToRLns0+cdwrIhLaQut+Cj4S2LRCwzMl
        fZ0oVQ7R26Ds+2akKq1qnWY7vmh+l4/C/DMWTiblwWM7l1nDH/1hmh8HYaxoxTzH
        ePv8M80CAwEAAaNjMGEwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAfYw
        HQYDVR0OBBYEFHsML5k8S+CTBufa93/qcpFiOaDJMB8GA1UdIwQYMBaAFHsML5k8
        S+CTBufa93/qcpFiOaDJMA0GCSqGSIb3DQEBBQUAA4GBAA61FS0kkYWzYVJtLrbv
        xuec7ttFNiYEFQt1+s/CSSHcXwISxPC3G/cqYsCzbqIZ33JfV0A0lihiPU85TFFq
        0eC2Vx8+/wYwwD0BNyXc/M5/WdjIJCmtMUctQPZG09FFNQ+4DdnvhxXdCsJwRw1x
        p1MY+FvHmFhom/BK5CWcU7eA
        -----END CERTIFICATE-----

coreos:
    units:
      - name: metadata-route.service
        command: start
        content: |
          [Unit]
          Description=Metadata Service Zeroconf Route
          Wants=network.target
          Before=network.target
          BindsTo=sys-subsystem-net-devices-ens32.device
          After=sys-subsystem-net-devices-ens32.device
  
          [Service]
          Type=oneshot
          RemainAfterExit=yes
          StandardOutput=journal+console
          ExecStart=/usr/bin/ip route add 169.254.0.0/16 dev ens32 scope link
      - name: vmtoolsd.service
        command: start
        content: |
          [Unit]
          Description=VMware Tools Agent
          Documentation=http://open-vm-tools.sourceforge.net/
          ConditionVirtualization=vmware
          [Service]
          ExecStartPre=/usr/bin/ln -sfT /usr/share/oem/vmware-tools /etc/vmware-tools
          ExecStart=/usr/share/oem/bin/vmtoolsd
          TimeoutStopSec=5
      - name: monsoon-certs.service
        command: start
        content: |
          [Unit]
          Description=Fetch Monsoon CA and machine certificates/keys
          Before=updatecertificates.service
          After=metadata-route.service
          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/usr/share/oem/bin/monsoon-certs
      - name: updatecertificates.service
        command: start
        content: |
          [Unit]
          Description=Update the certificates w/ self-signed root CAs
          Before=etcd.service
          Before=docker.service

          [Service]
          ExecStart=/usr/sbin/update-ca-certificates
          RemainAfterExit=yes
          Type=oneshot
      - name: oem-cloudinit.service
        command: restart
        runtime: yes
        content: |
          [Unit]
          Description=Cloudinit from EC2-style metadata

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/coreos-cloudinit --from-metadata-service
      - name: ntpd.service
        command: restart
      - name: docker.service
        command: restart
      - name: update-engine.service
        command: restart
      - name: mcollective-registration.service
        command: start
        content: |
          [Unit]
          Description=Publish Facts to Monsoon
          After=docker.service
          After=metadata-route.service

          [Service]
          Type=oneshot
          TimeoutStartSec=120s
          EnvironmentFile=/etc/environment
          ExecStartPre=/usr/bin/docker pull docker.mo.sap.corp/monsoon/mcollective-registration
          ExecStart=/usr/share/oem/bin/mcollective-registration
      - name: mcollective-registration.timer
        command: start
        content: |
          [Timer]
          OnCalendar=hourly
          OnBootSec=15s
          Unit=mcollective-registration.service
    oem:
      id: sap-monsoon
      name: SAP Monsoon
      version-id: @@OEM_VERSION_ID@@
      home-url: https://monsoon.mo.sap.corp/
      bug-report-url: https://github.com/coreos/bugs/issues
