#cloud-config

users:
  - name: lroot
    groups:
      - sudo
      - docker
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvFapuevZeHFpFn438XMjvEQYd0wt7+tzUdAkMiSd007Tx1h79Xm9ZziDDUe4W6meinVOq93MAS/ER27hoVWGo2H/vn/Cz5M8xr2j5rQODnrF3RmfrJTbZAWaDN0JTq2lFjmCHhZJNhr+VQP1uw4z2ofMBP6MLybnLmm9ukzxFYZqCCyfEEUTCMA9SWywtTpGQp8VLM4INCxzBSCuyt3SO6PBvJSo4HoKg/sLvmRwpCVZth48PI0EUbJ72wp88Cw3bv8CLce2TOkLMwkE6NRN55w2aOyqP1G3vixHa6YcVaLlkQhJoJsBwE3rX5603y2KjOhMomqHfXxXn/3GKTWlsQ==
  - name: core
    groups:
      - sudo
      - core
    passwd: $1$TwAGbIPv$Z25ZDN5NVJK3sTj.OsGiY0

write_files:
    - path: /etc/environment
      permissions: 0644
      content: |
        COREOS_PRIVATE_IPV4=$public_ipv4
        all_proxy=http://proxy.wdf.sap.corp:8080
        http_proxy=http://proxy.wdf.sap.corp:8080
        https_proxy=http://proxy.wdf.sap.corp:8080
        ftp_proxy=http://proxy.wdf.sap.corp:8080
        no_proxy=sap.corp,localhost,127.0.0.1,169.254.169.254
    - path: /etc/systemd/system/docker.service.d/10-proxy.conf
      permissions: 0644
      content: |
        [Service]
        EnvironmentFile=/etc/environment
    - path: /etc/systemd/system/update-engine.service.d/10-proxy.conf
      permissions: 0644
      content: |
        [Service]
        EnvironmentFile=/etc/environment
    - path: /etc/ntp.conf
      permissions: 0644
      content: |
        server timehost1.wdf.sap.corp
        server timehost2.wdf.sap.corp
        server timehost3.wdf.sap.corp

        restrict default nomodify nopeer noquery limited kod
        restrict 127.0.0.1
        restrict [::1]
    - path: /run/systemd/network/10-dhcp.network
      permissions: 0644
      content: |
        [Network]
        DHCP=true

        [DHCP]
        UseMTU=true
        UseHostname=false
        UseRoutes=true
        CriticalConnection=true
    - path: /run/systemd/system/etcd.service.d/10-oem.conf
      permissions: 0644
      content: |
        [Service]
        Environment=ETCD_PEER_ELECTION_TIMEOUT=1200
    - path: /etc/ssl/certs/SAPNetCA.pem
      permission: 0644
      content: |
        -----BEGIN CERTIFICATE-----
        MIICrjCCAhegAwIBAgIEAQAAADANBgkqhkiG9w0BAQUFADBpMQswCQYDVQQGEwJE
        RTEPMA0GA1UEChMGU0FQLUFHMQ8wDQYDVQQLEwZTQVBOZXQxETAPBgNVBAMTCFNB
        UE5ldENBMSUwIwYJKoZIhvcNAQkBFhZtYWlrLm11ZWxsZXJAc2FwLWFnLmRlMB4X
        DTk4MDUwNDExNTYzNFoXDTE1MDcxODEyMDAwMFowaTELMAkGA1UEBhMCREUxDzAN
        BgNVBAoTBlNBUC1BRzEPMA0GA1UECxMGU0FQTmV0MREwDwYDVQQDEwhTQVBOZXRD
        QTElMCMGCSqGSIb3DQEJARYWbWFpay5tdWVsbGVyQHNhcC1hZy5kZTCBnzANBgkq
        hkiG9w0BAQEFAAOBjQAwgYkCgYEA35NK6MmmrCLvur4BDhugFe2FUfwJlvErafBb
        fvn+mkn8jxC/Kl0trTsQADJzYUnCdDLyToRLns0+cdwrIhLaQut+Cj4S2LRCwzMl
        fZ0oVQ7R26Ds+2akKq1qnWY7vmh+l4/C/DMWTiblwWM7l1nDH/1hmh8HYaxoxTzH
        ePv8M80CAwEAAaNjMGEwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAfYw
        HQYDVR0OBBYEFHsML5k8S+CTBufa93/qcpFiOaDJMB8GA1UdIwQYMBaAFHsML5k8
        S+CTBufa93/qcpFiOaDJMA0GCSqGSIb3DQEBBQUAA4GBAA61FS0kkYWzYVJtLrbv
        xuec7ttFNiYEFQt1+s/CSSHcXwISxPC3G/cqYsCzbqIZ33JfV0A0lihiPU85TFFq
        0eC2Vx8+/wYwwD0BNyXc/M5/WdjIJCmtMUctQPZG09FFNQ+4DdnvhxXdCsJwRw1x
        p1MY+FvHmFhom/BK5CWcU7eA
        -----END CERTIFICATE-----

coreos:
    units:
      - name: updatecertificates.service
        command: start
        content: |
          [Unit]
          Description=Update the certificates w/ self-signed root CAs
          Before=etcd.service
          Before=docker.service

          [Service]
          ExecStart=/usr/sbin/update-ca-certificates
          RemainAfterExit=yes
          Type=oneshot
      - name: metadata-route.service
        command: start
        content: |
          [Unit]
          Description=Metadata Service Zeroconf Route
          Wants=network.target
          Before=network.target
          BindsTo=sys-subsystem-net-devices-ens32.device
          After=sys-subsystem-net-devices-ens32.device
  
          [Service]
          Type=oneshot
          RemainAfterExit=yes
          StandardOutput=journal+console
          ExecStart=/usr/bin/ip route add 169.254.0.0/16 dev ens32 scope link
      - name: monsoon-mcollective.service
        command: start
        content: |
          [Unit]
          Description=Monsoon mCollective
          After=docker.service
          After=metadata-route.service

          [Service]
          Restart=always
          TimeoutStartSec=1200s
          EnvironmentFile=/etc/environment
          ExecStartPre=-/usr/bin/docker rm -f mco
          ExecStartPre=-/usr/bin/docker pull docker.mo.sap.corp/monsoon/mcollective 
          ExecStart=/usr/bin/docker run --name mco -d -v /:/host docker.mo.sap.corp/monsoon/mcollective 
          ExecStop=/usr/bin/docker stop mco
      - name: vmware-tools.service
        command: start
        content: |
          [Unit]
          Description=VMWare Tools
          After=systemd-networkd.service
          After=docker.service

          [Service]
          Restart=always
          TimeoutStartSec=1200s
          ExecStartPre=-/usr/bin/docker rm -f vmware-tools
          ExecStartPre=-/usr/bin/docker pull docker.mo.sap.corp/monsoon/vmware-tools
          ExecStart=/usr/bin/docker run --net=host --privileged --name vmware-tools docker.mo.sap.corp/monsoon/vmware-tools
          ExecStop=/usr/bin/docker stop vmware-tools
      - name: oem-cloudinit.service
        command: restart
        runtime: yes
        content: |
          [Unit]
          Description=Cloudinit from EC2-style metadata

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/coreos-cloudinit --from-metadata-service
      - name: docker-tcp.socket
        command: start
        enable: yes
        content: |
          [Unit]
          Description=Docker Socket for the API

          [Socket]
          ListenStream=2375
          BindIPv6Only=both
          Service=docker.service

          [Install]
          WantedBy=sockets.target
      - name: enable-docker-tcp.service
        command: start
        content: |
          [Unit]
          Description=Enable the Docker Socket for the API

          [Service]
          ExecStartPre=/usr/bin/systemctl stop docker.socket
          ExecStartPre=/usr/bin/systemctl stop docker-tcp.socket
          ExecStartPre=/usr/bin/systemctl stop docker
          ExecStart=/usr/bin/systemctl enable docker-tcp.socket
          ExecStartPost=/usr/bin/systemctl start docker.socket
          ExecStartPost=/usr/bin/systemctl start docker-tcp.socket
          Type=oneshot
          RemainAfterExit=true
      - name: etcd.service
        command: start
      - name: fleet.service
        command: start
      - name: ntpd.service
        command: restart
      - name: docker.service
        command: restart
      - name: update-engine.service
        command: restart
    oem:
      id: sap-monsoon
      name: SAP Monsoon
      version-id: @@OEM_VERSION_ID@@
      home-url: https://monsoon.mo.sap.corp/
      bug-report-url: https://github.com/coreos/bugs/issues
